# Recommended multipath configuration for Hitachi VSP storage
# Copy to /etc/multipath/conf.d/hitachiblock-vsp.conf

devices {
    device {
        vendor                  "HITACHI"
        product                 "OPEN-V"
        path_grouping_policy    group_by_prio
        path_selector           "round-robin 0"
        prio                    alua
        failback                immediate
        no_path_retry           6
        rr_min_io_rq            1
        detect_prio             yes
        fast_io_fail_tmo        5
        dev_loss_tmo            30
    }
}
